### ISSUE TITLE
Implementation of visual gameplay

### ISSUE THREAD

**Issue by miselico** [intelligent-systems-course/schnapsen#7]

**Comment by tae898** [comment]
Assignee: Tae

**Comment by tae898** [comment]
TK: There are several classes that have a “state”: `BotState` ,`GameState`, `PlayerGameState`, `LeaderGameState`, `FollowerGameState`. Which one of them should have the method convert_to_json() so that Flask can handle the state? (edited) 

MC: `Playergamestate.` But, we do not add the conversion directly on that class. We can create our own class which has precisely what we need.
